workflows:
  react-native-expo-apk:
    name: Build Expo APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: Encrypted(put_your_token_here)
      node: 20
      npm: 9
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: npx expo export && npx eas build -p android --profile preview --non-interactive
    artifacts:
      - build/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
